
import { NounDefinition } from '../types';

// Format: [Artikel, Singular, Plural]
// Artikel: 'der', 'die', 'das'
// Plural: '-' bedeutet, das Wort hat keinen gebräuchlichen Plural (Singularetantum) oder wird hier nicht abgefragt.
const RAW_NOUN_DB: [string, string, string][] = [
  // --- A ---
  ['der', 'Abend', 'Abende'],
  ['das', 'Abendessen', 'Abendessen'],
  ['das', 'Abenteuer', 'Abenteuer'],
  ['die', 'Abfahrt', 'Abfahrten'],
  ['der', 'Abfall', 'Abfälle'],
  ['die', 'Absicht', 'Absichten'],
  ['die', 'Adresse', 'Adressen'],
  ['der', 'Affe', 'Affen'],
  ['die', 'Ahnung', 'Ahnungen'],
  ['die', 'Aktion', 'Aktionen'],
  ['das', 'Alter', '-'],
  ['die', 'Ampel', 'Ampeln'],
  ['das', 'Amt', 'Ämter'],
  ['der', 'Anfang', 'Anfänge'],
  ['das', 'Angebot', 'Angebote'],
  ['die', 'Angst', 'Ängste'],
  ['der', 'Anruf', 'Anrufe'],
  ['die', 'Antwort', 'Antworten'],
  ['der', 'Anzug', 'Anzüge'],
  ['der', 'Apfel', 'Äpfel'],
  ['die', 'Apotheke', 'Apotheken'],
  ['die', 'Arbeit', 'Arbeiten'],
  ['der', 'Arbeiter', 'Arbeiter'],
  ['der', 'Arm', 'Arme'],
  ['die', 'Art', 'Arten'],
  ['der', 'Arzt', 'Ärzte'],
  ['die', 'Ärztin', 'Ärztinnen'],
  ['der', 'Ast', 'Äste'],
  ['die', 'Aufgabe', 'Aufgaben'],
  ['das', 'Auge', 'Augen'],
  ['der', 'Augenblick', 'Augenblicke'],
  ['das', 'Ausland', '-'],
  ['die', 'Ausnahme', 'Ausnahmen'],
  ['das', 'Auto', 'Autos'],
  ['die', 'Autobahn', 'Autobahnen'],
  // --- B ---
  ['das', 'Baby', 'Babys'],
  ['der', 'Bach', 'Bäche'],
  ['das', 'Bad', 'Bäder'],
  ['die', 'Bahn', 'Bahnen'],
  ['der', 'Bahnhof', 'Bahnhöfe'],
  ['der', 'Ball', 'Bälle'],
  ['die', 'Banane', 'Bananen'],
  ['das', 'Band', 'Bänder'],
  ['die', 'Bank', 'Banken'],
  ['der', 'Bär', 'Bären'],
  ['der', 'Bart', 'Bärte'],
  ['der', 'Bau', 'Bauten'],
  ['der', 'Bauch', 'Bäuche'],
  ['der', 'Baum', 'Bäume'],
  ['das', 'Bein', 'Beine'],
  ['das', 'Beispiel', 'Beispiele'],
  ['der', 'Berg', 'Berge'],
  ['der', 'Beruf', 'Berufe'],
  ['das', 'Bett', 'Betten'],
  ['die', 'Bevölkerung', '-'],
  ['die', 'Bewegung', 'Bewegungen'],
  ['der', 'Beweis', 'Beweise'],
  ['das', 'Bier', 'Biere'],
  ['das', 'Bild', 'Bilder'],
  ['der', 'Bildschirm', 'Bildschirme'],
  ['das', 'Billett', 'Billette'],
  ['die', 'Birne', 'Birnen'],
  ['die', 'Bitte', 'Bitten'],
  ['das', 'Blatt', 'Blätter'],
  ['der', 'Bleistift', 'Bleistifte'],
  ['der', 'Blick', 'Blicke'],
  ['der', 'Blitz', 'Blitze'],
  ['die', 'Blume', 'Blumen'],
  ['die', 'Bluse', 'Blusen'],
  ['das', 'Blut', '-'],
  ['der', 'Boden', 'Böden'],
  ['die', 'Bohne', 'Bohnen'],
  ['das', 'Boot', 'Boote'],
  ['die', 'Botschaft', 'Botschaften'],
  ['der', 'Brand', 'Brände'],
  ['der', 'Brief', 'Briefe'],
  ['die', 'Brille', 'Brillen'],
  ['das', 'Brot', 'Brote'],
  ['das', 'Brötchen', 'Brötchen'],
  ['die', 'Brücke', 'Brücken'],
  ['der', 'Bruder', 'Brüder'],
  ['das', 'Buch', 'Bücher'],
  ['die', 'Bühne', 'Bühnen'],
  ['der', 'Bund', 'Bünde'],
  ['die', 'Burg', 'Burgen'],
  ['der', 'Bus', 'Busse'],
  ['die', 'Butter', '-'],
  // --- C ---
  ['das', 'Café', 'Cafés'],
  ['die', 'Chance', 'Chancen'],
  ['der', 'Chef', 'Chefs'],
  ['der', 'Chor', 'Chöre'],
  ['der', 'Club', 'Clubs'],
  ['der', 'Computer', 'Computer'],
  ['die', 'Creme', 'Cremes'],
  // --- D ---
  ['das', 'Dach', 'Dächer'],
  ['die', 'Dame', 'Damen'],
  ['der', 'Dank', '-'],
  ['das', 'Datum', 'Daten'],
  ['die', 'Decke', 'Decken'],
  ['der', 'Dichter', 'Dichter'],
  ['der', 'Dienst', 'Dienste'],
  ['der', 'Dienstag', 'Dienstage'],
  ['das', 'Ding', 'Dinge'],
  ['der', 'Doktor', 'Doktoren'],
  ['der', 'Dom', 'Dome'],
  ['der', 'Donner', 'Donner'],
  ['der', 'Donnerstag', 'Donnerstage'],
  ['das', 'Dorf', 'Dörfer'],
  ['der', 'Dreck', '-'],
  ['der', 'Druck', 'Drücke'],
  ['der', 'Duft', 'Düfte'],
  ['die', 'Dummheit', 'Dummheiten'],
  ['der', 'Durst', '-'],
  // --- E ---
  ['die', 'Ecke', 'Ecken'],
  ['die', 'Ehe', 'Ehen'],
  ['die', 'Ehre', 'Ehren'],
  ['das', 'Ei', 'Eier'],
  ['die', 'Eifersucht', '-'],
  ['der', 'Eimer', 'Eimer'],
  ['der', 'Eindruck', 'Eindrücke'],
  ['der', 'Einfluss', 'Einflüsse'],
  ['der', 'Eingang', 'Eingänge'],
  ['die', 'Einheit', 'Einheiten'],
  ['das', 'Eis', '-'],
  ['das', 'Eisen', '-'],
  ['der', 'Elefant', 'Elefanten'],
  ['die', 'Eltern', '-'], // Pluralwort
  ['das', 'Ende', 'Enden'],
  ['die', 'Energie', 'Energien'],
  ['der', 'Enkel', 'Enkel'],
  ['die', 'Ente', 'Enten'],
  ['die', 'Entscheidung', 'Entscheidungen'],
  ['die', 'Erde', '-'],
  ['das', 'Ergebnis', 'Ergebnisse'],
  ['die', 'Erinnerung', 'Erinnerungen'],
  ['die', 'Erklärung', 'Erklärungen'],
  ['die', 'Erlaubnis', 'Erlaubnisse'],
  ['der', 'Erwachsene', 'Erwachsenen'],
  ['das', 'Essen', 'Essen'],
  ['der', 'Euro', 'Euro'],
  // --- F ---
  ['die', 'Fabrik', 'Fabriken'],
  ['das', 'Fach', 'Fächer'],
  ['der', 'Faden', 'Fäden'],
  ['die', 'Fähigkeit', 'Fähigkeiten'],
  ['die', 'Fahrt', 'Fahrten'],
  ['der', 'Fall', 'Fälle'],
  ['die', 'Familie', 'Familien'],
  ['die', 'Farbe', 'Farben'],
  ['der', 'Fehler', 'Fehler'],
  ['die', 'Feier', 'Feiern'],
  ['das', 'Feld', 'Felder'],
  ['das', 'Fenster', 'Fenster'],
  ['die', 'Ferien', 'Ferien'],
  ['das', 'Fernsehen', '-'],
  ['das', 'Fest', 'Feste'],
  ['das', 'Feuer', 'Feuer'],
  ['die', 'Figur', 'Figuren'],
  ['der', 'Film', 'Filme'],
  ['der', 'Finger', 'Finger'],
  ['die', 'Firma', 'Firmen'],
  ['der', 'Fisch', 'Fische'],
  ['die', 'Fläche', 'Flächen'],
  ['die', 'Flamme', 'Flammen'],
  ['die', 'Flasche', 'Flaschen'],
  ['das', 'Fleisch', '-'],
  ['der', 'Fleiß', '-'],
  ['die', 'Fliege', 'Fliegen'],
  ['der', 'Flughafen', 'Flughäfen'],
  ['das', 'Flugzeug', 'Flugzeuge'],
  ['der', 'Fluss', 'Flüsse'],
  ['die', 'Folge', 'Folgen'],
  ['die', 'Form', 'Formen'],
  ['das', 'Foto', 'Fotos'],
  ['die', 'Frage', 'Fragen'],
  ['die', 'Frau', 'Frauen'],
  ['die', 'Freiheit', 'Freiheiten'],
  ['die', 'Freizeit', '-'],
  ['der', 'Freitag', 'Freitage'],
  ['der', 'Fremde', 'Fremden'],
  ['die', 'Freude', 'Freuden'],
  ['der', 'Freund', 'Freunde'],
  ['die', 'Freundin', 'Freundinnen'],
  ['die', 'Freundschaft', 'Freundschaften'],
  ['der', 'Frieden', '-'],
  ['der', 'Frühling', 'Frühlinge'],
  ['das', 'Frühstück', 'Frühstücke'],
  ['der', 'Fuchs', 'Füchse'],
  ['der', 'Füller', 'Füller'],
  ['die', 'Furcht', '-'],
  ['der', 'Fuß', 'Füße'],
  ['der', 'Fußball', 'Fußbälle'],
  // --- G ---
  ['die', 'Gabel', 'Gabeln'],
  ['der', 'Gang', 'Gänge'],
  ['die', 'Gans', 'Gänse'],
  ['die', 'Garage', 'Garagen'],
  ['die', 'Gardine', 'Gardinen'],
  ['der', 'Garten', 'Gärten'],
  ['der', 'Gast', 'Gäste'],
  ['das', 'Gebäude', 'Gebäude'],
  ['das', 'Gebiet', 'Gebiete'],
  ['das', 'Gebirge', 'Gebirge'],
  ['das', 'Gebot', 'Gebote'],
  ['die', 'Geburt', 'Geburten'],
  ['der', 'Geburtstag', 'Geburtstage'],
  ['der', 'Gedanke', 'Gedanken'],
  ['das', 'Gedicht', 'Gedichte'],
  ['die', 'Geduld', '-'],
  ['die', 'Gefahr', 'Gefahren'],
  ['das', 'Gefühl', 'Gefühle'],
  ['der', 'Gegensatz', 'Gegensätze'],
  ['der', 'Gegenstand', 'Gegenstände'],
  ['die', 'Gegend', 'Gegenden'],
  ['das', 'Gegenteil', 'Gegenteile'],
  ['das', 'Geheimnis', 'Geheimnisse'],
  ['der', 'Geist', 'Geister'],
  ['das', 'Geld', 'Gelder'],
  ['die', 'Gelegenheit', 'Gelegenheiten'],
  ['das', 'Gemüse', '-'],
  ['das', 'Gerät', 'Geräte'],
  ['das', 'Gericht', 'Gerichte'],
  ['das', 'Geräusch', 'Geräusche'],
  ['der', 'Geruch', 'Gerüche'],
  ['das', 'Geschäft', 'Geschäfte'],
  ['das', 'Geschenk', 'Geschenke'],
  ['die', 'Geschichte', 'Geschichten'],
  ['das', 'Geschirr', '-'],
  ['der', 'Geschmack', 'Geschmäcker'],
  ['die', 'Geschwindigkeit', 'Geschwindigkeiten'],
  ['die', 'Gesellschaft', 'Gesellschaften'],
  ['das', 'Gesetz', 'Gesetze'],
  ['das', 'Gesicht', 'Gesichter'],
  ['das', 'Gespräch', 'Gespräche'],
  ['die', 'Gesundheit', '-'],
  ['das', 'Getränk', 'Getränke'],
  ['die', 'Gewalt', 'Gewalten'],
  ['das', 'Gewicht', 'Gewichte'],
  ['der', 'Gewinn', 'Gewinne'],
  ['das', 'Gewitter', 'Gewitter'],
  ['das', 'Gewissen', '-'],
  ['die', 'Gitarre', 'Gitarren'],
  ['das', 'Glas', 'Gläser'],
  ['die', 'Glocke', 'Glocken'],
  ['das', 'Glück', '-'],
  ['das', 'Gold', '-'],
  ['der', 'Gott', 'Götter'],
  ['das', 'Grab', 'Gräber'],
  ['das', 'Gras', 'Gräser'],
  ['die', 'Grenze', 'Grenzen'],
  ['die', 'Größe', 'Größen'],
  ['die', 'Großmutter', 'Großmütter'],
  ['der', 'Großvater', 'Großväter'],
  ['die', 'Gruppe', 'Gruppen'],
  ['der', 'Gruß', 'Grüße'],
  ['die', 'Gurke', 'Gurken'],
  ['der', 'Gürtel', 'Gürtel'],
  // --- H ---
  ['das', 'Haar', 'Haare'],
  ['der', 'Hafen', 'Häfen'],
  ['der', 'Hahn', 'Hähne'],
  ['der', 'Hai', 'Haie'],
  ['die', 'Hälfte', 'Hälften'],
  ['der', 'Hals', 'Hälse'],
  ['der', 'Hammer', 'Hämmer'],
  ['die', 'Hand', 'Hände'],
  ['der', 'Handel', '-'],
  ['das', 'Handy', 'Handys'],
  ['das', 'Handtuch', 'Handtücher'],
  ['der', 'Hase', 'Hasen'],
  ['der', 'Hass', '-'],
  ['das', 'Haus', 'Häuser'],
  ['die', 'Hausaufgabe', 'Hausaufgaben'],
  ['die', 'Haut', 'Häute'],
  ['das', 'Heft', 'Hefte'],
  ['die', 'Heimat', '-'],
  ['der', 'Held', 'Helden'],
  ['das', 'Hemd', 'Hemden'],
  ['der', 'Herbst', 'Herbste'],
  ['der', 'Herd', 'Herde'],
  ['der', 'Herr', 'Herren'],
  ['das', 'Herz', 'Herzen'],
  ['die', 'Hexe', 'Hexen'],
  ['die', 'Hilfe', 'Hilfen'],
  ['der', 'Himmel', '-'],
  ['die', 'Hitze', '-'],
  ['das', 'Hobby', 'Hobbys'],
  ['die', 'Höhe', 'Höhen'],
  ['die', 'Höhle', 'Höhlen'],
  ['das', 'Holz', 'Hölzer'],
  ['der', 'Honig', '-'],
  ['das', 'Horn', 'Hörner'],
  ['die', 'Hose', 'Hosen'],
  ['das', 'Hotel', 'Hotels'],
  ['das', 'Huhn', 'Hühner'],
  ['der', 'Hund', 'Hunde'],
  ['der', 'Hunger', '-'],
  ['der', 'Hut', 'Hüte'],
  // --- I ---
  ['die', 'Idee', 'Ideen'],
  ['der', 'Igel', 'Igel'],
  ['die', 'Industrie', 'Industrien'],
  ['der', 'Inhalt', 'Inhalte'],
  ['das', 'Insekt', 'Insekten'],
  ['die', 'Insel', 'Inseln'],
  ['das', 'Instrument', 'Instrumente'],
  ['das', 'Interesse', 'Interessen'],
  ['das', 'Internet', '-'],
  ['der', 'Irrtum', 'Irrtümer'],
  // --- J ---
  ['die', 'Jacke', 'Jacken'],
  ['die', 'Jagd', 'Jagden'],
  ['das', 'Jahr', 'Jahre'],
  ['die', 'Jahreszeit', 'Jahreszeiten'],
  ['das', 'Jahrhundert', 'Jahrhunderte'],
  ['der', 'Januar', 'Januare'],
  ['die', 'Jeans', 'Jeans'],
  ['die', 'Jugend', '-'],
  ['der', 'Jugendliche', 'Jugendlichen'],
  ['der', 'Juli', 'Julis'],
  ['der', 'Juni', 'Junis'],
  ['der', 'Junge', 'Jungen'],
  // --- K ---
  ['der', 'Kaffee', '-'],
  ['der', 'Käfig', 'Käfige'],
  ['der', 'Kaiser', 'Kaiser'],
  ['das', 'Kalb', 'Kälber'],
  ['der', 'Kalender', 'Kalender'],
  ['die', 'Kälte', '-'],
  ['das', 'Kamel', 'Kamele'],
  ['die', 'Kamera', 'Kameras'],
  ['der', 'Kamerad', 'Kameraden'],
  ['der', 'Kampf', 'Kämpfe'],
  ['das', 'Kaninchen', 'Kaninchen'],
  ['die', 'Kanne', 'Kannen'],
  ['die', 'Karte', 'Karten'],
  ['die', 'Kartoffel', 'Kartoffeln'],
  ['der', 'Käse', 'Käse'],
  ['die', 'Kasse', 'Kassen'],
  ['der', 'Kasten', 'Kästen'],
  ['die', 'Katze', 'Katzen'],
  ['der', 'Keller', 'Keller'],
  ['der', 'Kellner', 'Kellner'],
  ['die', 'Kerze', 'Kerzen'],
  ['die', 'Kette', 'Ketten'],
  ['das', 'Kind', 'Kinder'],
  ['der', 'Kindergarten', 'Kindergärten'],
  ['das', 'Kino', 'Kinos'],
  ['die', 'Kirche', 'Kirchen'],
  ['die', 'Kirsche', 'Kirschen'],
  ['das', 'Kissen', 'Kissen'],
  ['die', 'Klasse', 'Klassen'],
  ['das', 'Kleid', 'Kleider'],
  ['die', 'Kleidung', 'Kleidungen'],
  ['das', 'Klima', 'Klimata'],
  ['das', 'Knie', 'Knie'],
  ['der', 'Knochen', 'Knochen'],
  ['der', 'Knopf', 'Knöpfe'],
  ['der', 'Koffer', 'Koffer'],
  ['der', 'Kollege', 'Kollegen'],
  ['der', 'König', 'Könige'],
  ['der', 'Kopf', 'Köpfe'],
  ['der', 'Körper', 'Körper'],
  ['die', 'Kosten', '-'],
  ['die', 'Kraft', 'Kräfte'],
  ['der', 'Kranke', 'Kranken'],
  ['das', 'Krankenhaus', 'Krankenhäuser'],
  ['die', 'Krankheit', 'Krankheiten'],
  ['der', 'Kreis', 'Kreise'],
  ['das', 'Kreuz', 'Kreuze'],
  ['der', 'Krieg', 'Kriege'],
  ['die', 'Kritik', 'Kritiken'],
  ['das', 'Krokodil', 'Krokodile'],
  ['die', 'Küche', 'Küchen'],
  ['der', 'Kuchen', 'Kuchen'],
  ['die', 'Kugel', 'Kugeln'],
  ['die', 'Kuh', 'Kühe'],
  ['der', 'Kunde', 'Kunden'],
  ['die', 'Kunst', 'Künste'],
  ['der', 'Künstler', 'Künstler'],
  ['der', 'Kuss', 'Küsse'],
  ['die', 'Küste', 'Küsten'],
  // --- L ---
  ['das', 'Lächeln', '-'],
  ['der', 'Laden', 'Läden'],
  ['die', 'Lage', 'Lagen'],
  ['das', 'Lager', 'Lager'],
  ['die', 'Lampe', 'Lampen'],
  ['das', 'Land', 'Länder'],
  ['die', 'Landschaft', 'Landschaften'],
  ['der', 'Lärm', '-'],
  ['die', 'Last', 'Lasten'],
  ['das', 'Laub', '-'],
  ['die', 'Laune', 'Launen'],
  ['das', 'Leben', 'Leben'],
  ['das', 'Lebensmittel', 'Lebensmittel'],
  ['das', 'Leder', '-'],
  ['der', 'Lehrer', 'Lehrer'],
  ['die', 'Lehrerin', 'Lehrerinnen'],
  ['die', 'Leiche', 'Leichen'],
  ['das', 'Leid', '-'],
  ['die', 'Leistung', 'Leistungen'],
  ['die', 'Leitung', 'Leitungen'],
  ['die', 'Leute', '-'],
  ['das', 'Licht', 'Lichter'],
  ['das', 'Lied', 'Lieder'],
  ['die', 'Liebe', '-'],
  ['die', 'Linie', 'Linien'],
  ['die', 'Lippe', 'Lippen'],
  ['die', 'Liste', 'Listen'],
  ['das', 'Loch', 'Löcher'],
  ['der', 'Löffel', 'Löffel'],
  ['der', 'Lohn', 'Löhne'],
  ['die', 'Lösung', 'Lösungen'],
  ['der', 'Löwe', 'Löwen'],
  ['die', 'Luft', 'Lüfte'],
  ['die', 'Lüge', 'Lügen'],
  ['die', 'Lust', '-'],
  // --- M ---
  ['das', 'Mädchen', 'Mädchen'],
  ['der', 'Magen', 'mägen'],
  ['der', 'Mai', '-'],
  ['das', 'Mal', 'Male'],
  ['der', 'Maler', 'Maler'],
  ['die', 'Mama', 'Mamas'],
  ['der', 'Mann', 'Männer'],
  ['der', 'Mantel', 'Mäntel'],
  ['das', 'Märchen', 'Märchen'],
  ['die', 'Markt', 'Märkte'],
  ['die', 'Maschine', 'Maschinen'],
  ['das', 'Material', 'Materialien'],
  ['die', 'Mauer', 'Mauern'],
  ['die', 'Maus', 'Mäuse'],
  ['das', 'Medikament', 'Medikamente'],
  ['das', 'Meer', 'Meere'],
  ['das', 'Mehl', '-'],
  ['die', 'Mehrheit', 'Mehrheiten'],
  ['die', 'Meinung', 'Meinungen'],
  ['die', 'Menge', 'Mengen'],
  ['der', 'Mensch', 'Menschen'],
  ['das', 'Messer', 'Messer'],
  ['das', 'Metall', 'Metalle'],
  ['die', 'Methode', 'Methoden'],
  ['die', 'Miete', 'Mieten'],
  ['die', 'Milch', '-'],
  ['die', 'Minute', 'Minuten'],
  ['der', 'Mittag', 'Mittage'],
  ['die', 'Mitte', '-'],
  ['das', 'Mittel', 'Mittel'],
  ['das', 'Möbel', 'Möbel'],
  ['die', 'Mode', 'Moden'],
  ['das', 'Modell', 'Modelle'],
  ['die', 'Möglichkeit', 'Möglichkeiten'],
  ['der', 'Moment', 'Momente'],
  ['der', 'Monat', 'Monate'],
  ['der', 'Mond', 'Monde'],
  ['der', 'Montag', 'Montage'],
  ['der', 'Morgen', 'Morgen'],
  ['der', 'Motor', 'Motoren'],
  ['die', 'Mühe', 'Mühen'],
  ['der', 'Müll', '-'],
  ['der', 'Mund', 'Münder'],
  ['die', 'Münze', 'Münzen'],
  ['das', 'Museum', 'Museen'],
  ['die', 'Musik', '-'],
  ['der', 'Muskel', 'Muskeln'],
  ['der', 'Mut', '-'],
  ['die', 'Mutter', 'Mütter'],
  ['die', 'Mütze', 'Mützen'],
  // --- N ---
  ['der', 'Nachbar', 'Nachbarn'],
  ['der', 'Nachmittag', 'Nachmittage'],
  ['die', 'Nachricht', 'Nachrichten'],
  ['die', 'Nacht', 'Nächte'],
  ['der', 'Nagel', 'Nägel'],
  ['die', 'Nahrung', '-'],
  ['der', 'Name', 'Namen'],
  ['die', 'Nase', 'Nasen'],
  ['die', 'Natur', '-'],
  ['der', 'Nebel', 'Nebel'],
  ['der', 'Neffe', 'Neffen'],
  ['das', 'Nest', 'Nester'],
  ['das', 'Netz', 'Netze'],
  ['die', 'Nichte', 'Nichten'],
  ['der', 'Nord', '-'],
  ['die', 'Note', 'Noten'],
  ['die', 'Not', 'Nöte'],
  ['die', 'Nudel', 'Nudeln'],
  ['die', 'Nummer', 'Nummern'],
  ['die', 'Nuss', 'Nüsse'],
  // --- O ---
  ['das', 'Obst', '-'],
  ['der', 'Ochse', 'Ochsen'],
  ['der', 'Ofen', 'Öfen'],
  ['das', 'Ohr', 'Ohren'],
  ['das', 'Öl', 'Öle'],
  ['die', 'Oma', 'Omas'],
  ['der', 'Onkel', 'Onkel'],
  ['der', 'Opa', 'Opas'],
  ['die', 'Oper', 'Opern'],
  ['die', 'Orange', 'Orangen'],
  ['die', 'Ordnung', 'Ordnungen'],
  ['das', 'Original', 'Originale'],
  ['der', 'Ort', 'Orte'],
  ['der', 'Osten', '-'],
  ['der', 'Ozean', 'Ozeane'],
  // --- P ---
  ['das', 'Paar', 'Paare'],
  ['das', 'Paket', 'Pakete'],
  ['der', 'Palast', 'Paläste'],
  ['die', 'Panik', '-'],
  ['das', 'Papier', 'Papiere'],
  ['das', 'Parfüm', 'Parfüms'],
  ['der', 'Park', 'Parks'],
  ['die', 'Partei', 'Parteien'],
  ['der', 'Partner', 'Partner'],
  ['die', 'Party', 'Partys'],
  ['der', 'Pass', 'Pässe'],
  ['die', 'Pause', 'Pausen'],
  ['das', 'Pech', '-'],
  ['die', 'Person', 'Personen'],
  ['der', 'Pfad', 'Pfade'],
  ['die', 'Pfanne', 'Pfannen'],
  ['der', 'Pfeffer', '-'],
  ['das', 'Pferd', 'Pferde'],
  ['die', 'Pflanze', 'Pflanzen'],
  ['das', 'Pflaster', 'Pflaster'],
  ['die', 'Pflicht', 'Pflichten'],
  ['die', 'Physik', '-'],
  ['der', 'Plan', 'Pläne'],
  ['der', 'Planet', 'Planeten'],
  ['die', 'Plastik', '-'],
  ['der', 'Platz', 'Plätze'],
  ['die', 'Politik', '-'],
  ['die', 'Polizei', '-'],
  ['die', 'Post', '-'],
  ['die', 'Postkarte', 'Postkarten'],
  ['der', 'Preis', 'Preise'],
  ['das', 'Problem', 'Probleme'],
  ['das', 'Produkt', 'Produkte'],
  ['das', 'Programm', 'Programme'],
  ['das', 'Projekt', 'Projekte'],
  ['der', 'Prozess', 'Prozesse'],
  ['die', 'Prüfung', 'Prüfungen'],
  ['der', 'Pullover', 'Pullover'],
  ['der', 'Punkt', 'Punkte'],
  ['die', 'Puppe', 'Puppen'],
  // --- Q ---
  ['die', 'Qualität', 'Qualitäten'],
  ['die', 'Quelle', 'Quellen'],
  ['die', 'Quittung', 'Quittungen'],
  // --- R ---
  ['der', 'Rabatt', 'Rabatte'],
  ['die', 'Rache', '-'],
  ['das', 'Rad', 'Räder'],
  ['das', 'Radio', 'Radios'],
  ['der', 'Rahmen', 'Rahmen'],
  ['der', 'Rand', 'Ränder'],
  ['der', 'Rat', 'Ratschläge'],
  ['das', 'Rätsel', 'Rätsel'],
  ['der', 'Raum', 'Räume'],
  ['die', 'Rechnung', 'Rechnungen'],
  ['das', 'Recht', 'Rechte'],
  ['die', 'Rede', 'Reden'],
  ['die', 'Regel', 'Regeln'],
  ['der', 'Regen', 'Regenfälle'],
  ['die', 'Regierung', 'Regierungen'],
  ['der', 'Reifen', 'Reifen'],
  ['die', 'Reihe', 'Reihen'],
  ['der', 'Reis', '-'],
  ['die', 'Reise', 'Reisen'],
  ['der', 'Rekord', 'Rekorde'],
  ['die', 'Religion', 'Religionen'],
  ['das', 'Rennen', 'Rennen'],
  ['die', 'Reparatur', 'Reparaturen'],
  ['die', 'Republik', 'Republiken'],
  ['der', 'Rest', 'Reste'],
  ['das', 'Restaurant', 'Restaurants'],
  ['die', 'Richtung', 'Richtungen'],
  ['der', 'Riese', 'Riesen'],
  ['das', 'Rind', 'Rinder'],
  ['der', 'Ring', 'Ringe'],
  ['das', 'Risiko', 'Risiken'],
  ['der', 'Rock', 'Röcke'],
  ['das', 'Rohr', 'Rohre'],
  ['die', 'Rolle', 'Rollen'],
  ['der', 'Roman', 'Romane'],
  ['die', 'Rose', 'Rosen'],
  ['der', 'Rücken', 'Rücken'],
  ['der', 'Rucksack', 'Rucksäcke'],
  ['die', 'Ruhe', '-'],
  ['die', 'Runde', 'Runden'],
  // --- S ---
  ['der', 'Saal', 'Säle'],
  ['die', 'Sache', 'Sachen'],
  ['der', 'Sack', 'Säcke'],
  ['der', 'Saft', 'Säfte'],
  ['die', 'Sahne', '-'],
  ['die', 'Saison', 'Saisons'],
  ['der', 'Salat', 'Salate'],
  ['das', 'Salz', 'Salze'],
  ['der', 'Samen', 'Samen'],
  ['der', 'Samstag', 'Samstage'],
  ['der', 'Sand', '-'],
  ['der', 'Sänger', 'Sänger'],
  ['der', 'Satz', 'Sätze'],
  ['die', 'Sau', 'Säue'],
  ['die', 'Schachtel', 'Schachteln'],
  ['der', 'Schaden', 'Schäden'],
  ['das', 'Schaf', 'Schafe'],
  ['der', 'Schal', 'Schals'],
  ['der', 'Schalter', 'Schalter'],
  ['die', 'Schande', '-'],
  ['der', 'Schatten', 'Schatten'],
  ['der', 'Schatz', 'Schätze'],
  ['die', 'Schau', 'Schauen'],
  ['die', 'Schaufel', 'Schaufeln'],
  ['der', 'Schauspieler', 'Schauspieler'],
  ['die', 'Scheibe', 'Scheiben'],
  ['die', 'Schere', 'Scheren'],
  ['der', 'Scherz', 'Scherze'],
  ['die', 'Schicht', 'Schichten'],
  ['das', 'Schicksal', 'Schicksale'],
  ['das', 'Schiff', 'Schiffe'],
  ['das', 'Schild', 'Schilder'],
  ['der', 'Schinken', 'Schinken'],
  ['der', 'Schirm', 'Schirme'],
  ['der', 'Schlaf', '-'],
  ['die', 'Schlange', 'Schlangen'],
  ['der', 'Schloss', 'Schlösser'],
  ['der', 'Schluss', 'Schlüsse'],
  ['der', 'Schlüssel', 'Schlüssel'],
  ['der', 'Schmerz', 'Schmerzen'],
  ['der', 'Schmetterling', 'Schmetterlinge'],
  ['der', 'Schmutz', '-'],
  ['der', 'Schnabel', 'Schnäbel'],
  ['der', 'Schnee', '-'],
  ['die', 'Schnecke', 'Schnecken'],
  ['der', 'Schneider', 'Schneider'],
  ['die', 'Schnur', 'Schnüre'],
  ['die', 'Schokolade', 'Schokoladen'],
  ['der', 'Schrank', 'Schränke'],
  ['der', 'Schreck', 'Schrecke'],
  ['der', 'Schrei', 'Schreie'],
  ['der', 'Schrift', 'Schriften'],
  ['der', 'Schritt', 'Schritte'],
  ['der', 'Schuh', 'Schuhe'],
  ['die', 'Schuld', 'Schulden'],
  ['die', 'Schule', 'Schulen'],
  ['der', 'Schüler', 'Schüler'],
  ['die', 'Schulter', 'Schultern'],
  ['der', 'Schutz', '-'],
  ['der', 'Schwanz', 'Schwänze'],
  ['das', 'Schwein', 'Schweine'],
  ['die', 'Schwester', 'Schwestern'],
  ['die', 'Schwierigkeit', 'Schwierigkeiten'],
  ['das', 'Schwimmbad', 'Schwimmbäder'],
  ['der', 'See', 'Seen'],
  ['die', 'Seele', 'Seelen'],
  ['das', 'Segel', 'Segel'],
  ['das', 'Seil', 'Seile'],
  ['die', 'Seite', 'Seiten'],
  ['der', 'Sekretär', 'Sekretäre'],
  ['die', 'Sekunde', 'Sekunden'],
  ['der', 'Senf', '-'],
  ['der', 'Sessel', 'Sessel'],
  ['die', 'Sicht', '-'],
  ['der', 'Sieg', 'Siege'],
  ['das', 'Silber', '-'],
  ['die', 'Silbe', 'Silben'],
  ['der', 'Sinn', 'Sinne'],
  ['die', 'Situation', 'Situationen'],
  ['der', 'Sitz', 'Sitze'],
  ['der', 'Sklave', 'Sklaven'],
  ['das', 'Sofa', 'Sofas'],
  ['der', 'Sohn', 'Söhne'],
  ['der', 'Soldat', 'Soldaten'],
  ['der', 'Sommer', 'Sommer'],
  ['die', 'Sonne', 'Sonnen'],
  ['der', 'Sonntag', 'Sonntage'],
  ['die', 'Sorge', 'Sorgen'],
  ['die', 'Soße', 'Soßen'],
  ['der', 'Spaß', 'Späße'],
  ['der', 'Spaziergang', 'Spaziergänge'],
  ['der', 'Speck', '-'],
  ['die', 'Speise', 'Speisen'],
  ['der', 'Spiegel', 'Spiegel'],
  ['das', 'Spiel', 'Spiele'],
  ['das', 'Spielzeug', 'Spielzeuge'],
  ['die', 'Spinne', 'Spinnen'],
  ['die', 'Spitze', 'Spitzen'],
  ['der', 'Sport', '-'],
  ['die', 'Sprache', 'Sprachen'],
  ['der', 'Spruch', 'Sprüche'],
  ['der', 'Sprung', 'Sprünge'],
  ['die', 'Spur', 'Spuren'],
  ['das', 'Stadion', 'Stadien'],
  ['der', 'Stadt', 'Städte'],
  ['der', 'Stahl', '-'],
  ['der', 'Stall', 'Ställe'],
  ['der', 'Stamm', 'Stämme'],
  ['der', 'Stand', 'Stände'],
  ['der', 'Star', 'Stars'],
  ['der', 'Start', 'Starts'],
  ['die', 'Station', 'Stationen'],
  ['die', 'Statue', 'Statuen'],
  ['der', 'Staub', '-'],
  ['das', 'Steak', 'Steaks'],
  ['der', 'Stein', 'Steine'],
  ['die', 'Stelle', 'Stellen'],
  ['der', 'Stempel', 'Stempel'],
  ['der', 'Stern', 'Sterne'],
  ['die', 'Steuer', 'Steuern'],
  ['der', 'Stiefel', 'Stiefel'],
  ['der', 'Stier', 'Stiere'],
  ['der', 'Stift', 'Stifte'],
  ['der', 'Stil', 'Stile'],
  ['die', 'Stimme', 'Stimmen'],
  ['die', 'Stimmung', 'Stimmungen'],
  ['die', 'Stirn', 'Stirnen'],
  ['der', 'Stock', 'Stöcke'],
  ['der', 'Stoff', 'Stoffe'],
  ['der', 'Stolz', '-'],
  ['die', 'Strafe', 'Strafen'],
  ['der', 'Strand', 'Strände'],
  ['die', 'Straße', 'Straßen'],
  ['die', 'Straßenbahn', 'Straßenbahnen'],
  ['der', 'Strauch', 'Sträucher'],
  ['der', 'Streich', 'Streiche'],
  ['der', 'Streik', 'Streiks'],
  ['der', 'Streit', 'Streite'],
  ['der', 'Strich', 'Striche'],
  ['der', 'Strom', '-'],
  ['der', 'Strumpf', 'Strümpfe'],
  ['das', 'Stück', 'Stücke'],
  ['der', 'Student', 'Studenten'],
  ['das', 'Studium', 'Studien'],
  ['der', 'Stuhl', 'Stühle'],
  ['die', 'Stunde', 'Stunden'],
  ['der', 'Sturm', 'Stürme'],
  ['die', 'Suche', '-'],
  ['die', 'Summe', 'Summen'],
  ['die', 'Sünde', 'Sünden'],
  ['die', 'Suppe', 'Suppen'],
  ['der', 'Süden', '-'],
  ['das', 'Symbol', 'Symbole'],
  ['das', 'System', 'Systeme'],
  ['die', 'Szene', 'Szenen'],
  // --- T ---
  ['die', 'Tabelle', 'Tabellen'],
  ['der', 'Tag', 'Tage'],
  ['die', 'Taille', 'Taillen'],
  ['das', 'Tal', 'Täler'],
  ['die', 'Tankstelle', 'Tankstellen'],
  ['die', 'Tante', 'Tanten'],
  ['der', 'Tanz', 'Tänze'],
  ['die', 'Tasche', 'Taschen'],
  ['die', 'Taschenlampe', 'Taschenlampen'],
  ['die', 'Tasse', 'Tassen'],
  ['die', 'Tat', 'Taten'],
  ['die', 'Tätigkeit', 'Tätigkeiten'],
  ['die', 'Tatsache', 'Tatsachen'],
  ['die', 'Taube', 'Tauben'],
  ['das', 'Taxi', 'Taxis'],
  ['das', 'Team', 'Teams'],
  ['die', 'Technik', 'Techniken'],
  ['der', 'Tee', 'Tees'],
  ['der', 'Teich', 'Teiche'],
  ['der', 'Teig', 'Teige'],
  ['der', 'Teil', 'Teile'],
  ['das', 'Telefon', 'Telefone'],
  ['der', 'Teller', 'Teller'],
  ['die', 'Temperatur', 'Temperaturen'],
  ['der', 'Tennis', '-'],
  ['der', 'Teppich', 'Teppiche'],
  ['der', 'Termin', 'Termine'],
  ['die', 'Terrasse', 'Terrassen'],
  ['der', 'Test', 'Tests'],
  ['der', 'Text', 'Texte'],
  ['das', 'Theater', 'Theater'],
  ['das', 'Thema', 'Themen'],
  ['die', 'Theorie', 'Theorien'],
  ['das', 'Ticket', 'Tickets'],
  ['die', 'Tiefe', 'Tiefen'],
  ['das', 'Tier', 'Tiere'],
  ['der', 'Tiger', 'Tiger'],
  ['die', 'Tinte', 'Tinten'],
  ['der', 'Tisch', 'Tische'],
  ['der', 'Titel', 'Titel'],
  ['die', 'Tochter', 'Töchter'],
  ['der', 'Tod', 'Tode'],
  ['die', 'Toilette', 'Toiletten'],
  ['die', 'Tomate', 'Tomaten'],
  ['der', 'Ton', 'Töne'],
  ['der', 'Topf', 'Töpfe'],
  ['das', 'Tor', 'Tore'],
  ['die', 'Torte', 'Torten'],
  ['der', 'Tourist', 'Touristen'],
  ['die', 'Träne', 'Tränen'],
  ['der', 'Transport', 'Transporte'],
  ['der', 'Traum', 'Träume'],
  ['die', 'Treppe', 'Treppen'],
  ['der', 'Tritt', 'Tritte'],
  ['der', 'Trost', '-'],
  ['das', 'Tuch', 'Tücher'],
  ['die', 'Tür', 'Türen'],
  ['der', 'Turm', 'Türme'],
  ['die', 'Tüte', 'Tüten'],
  ['der', 'Typ', 'Typen'],
];

// --- LOGIK FÜR OFFLINE ANALYSE ---

let REVERSE_NOUN_INDEX: Map<string, NounDefinition> | null = null;

const buildNounIndex = () => {
  if (REVERSE_NOUN_INDEX) return;
  REVERSE_NOUN_INDEX = new Map();

  RAW_NOUN_DB.forEach(([article, singular, plural]) => {
    const def: NounDefinition = {
      original: singular, // Fallback
      lemma: singular,
      article: article,
      plural: plural,
      pluralArticle: 'die'
    };

    // 1. Indexiere Singular (lowercase)
    REVERSE_NOUN_INDEX!.set(singular.toLowerCase(), def);

    // 2. Indexiere Plural (lowercase) - Verweist auf das GLEICHE Definitionsobjekt
    // Dadurch wird "Wolken" gefunden und liefert { lemma: "Wolke", ... } zurück
    if (plural !== singular && plural !== '-') {
        REVERSE_NOUN_INDEX!.set(plural.toLowerCase(), def);
    }
  });
};

export const analyzeTextLocalNouns = (text: string): NounDefinition[] => {
  buildNounIndex();
  const found: NounDefinition[] = [];
  
  // Einfache Tokenisierung: Alles außer Buchstaben entfernen, aber Umlaute behalten
  const cleanText = text.replace(/[.,!?;:"]/g, ' ');
  const words = cleanText.split(/\s+/);

  words.forEach(word => {
    const w = word.trim();
    if (w.length < 2) return;

    const lower = w.toLowerCase();
    const match = REVERSE_NOUN_INDEX?.get(lower);

    if (match) {
      // Wir erstellen eine Kopie, damit "original" das tatsächlich gefundene Wort im Text ist (z.B. "Wolken")
      found.push({
        ...match,
        original: word
      });
    }
  });

  // Duplikate entfernen (basierend auf Lemma)
  const unique = new Map<string, NounDefinition>();
  found.forEach(item => {
      if (!unique.has(item.lemma)) {
          unique.set(item.lemma, item);
      }
  });

  return Array.from(unique.values());
};

export const getNounData = (lemma: string): NounDefinition | null => {
    buildNounIndex();
    return REVERSE_NOUN_INDEX?.get(lemma.toLowerCase()) || null;
};

// Initialize index asynchronously on load
setTimeout(buildNounIndex, 200);
